name: New User

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types: opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        python3 build.py
    - name: Commit files
      run: |
        git config --local user.email "bot@colewilson.xyz"
        git config --local user.name "[bot]"
        git add -A
        git commit -m "Update Projects" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
